import { Component, Input, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SfckMarkComponent } from '../../../shared/components/icon/sfck-mark.component';
import { DataService } from '../../../core/services/data.service';

@Component({
  selector: 'app-payslip-header',
  standalone: true,
  imports: [CommonModule, SfckMarkComponent],
  template: `
    <div style="padding: 18px 24px; border-bottom: 2px solid var(--ink); background: var(--bg-2);">
      <div class="row" style="align-items: flex-start;">
        <div>
          <div style="font-size: 11px; color: var(--ink-3); letter-spacing: 0.14em; text-transform: uppercase; font-weight: 700;">The State Farming Corporation of Kerala Ltd.</div>
          <div class="ml" style="font-size: 11px; color: var(--ink-3); margin-top: 2px;">കേരള സ്റ്റേറ്റ് ഫാമിംഗ് കോർപ്പറേഷൻ ലിമിറ്റഡ്</div>
          <div style="font-size: 22px; font-weight: 800; margin-top: 6px; letter-spacing: -0.01em;">
            Wage Slip
            @if (lang !== 'en') {
              <span class="ml" style="font-weight: 600; font-size: 18px; color: var(--ink-2);"> · വേതന ചീട്ട്</span>
            }
          </div>
          <div class="muted" style="font-size: 12px; margin-top: 2px;">Kulathupuzha Estate · CIN U01122KL1972SGC002545</div>
        </div>
        <div style="margin-left: auto; text-align: right;">
          <app-sfck-mark [size]="36"></app-sfck-mark>
          <div class="mono muted" style="font-size: 10px; margin-top: 6px;">Generated by<br/>SFCK · Estate Operations</div>
        </div>
      </div>
    </div>
  `
})
export class PayslipHeaderComponent {
  @Input() lang = 'both';
}

@Component({
  selector: 'app-payslip-a',
  standalone: true,
  imports: [CommonModule, PayslipHeaderComponent],
  template: `
    <div style="max-width: 820px; margin: 0 auto; background: var(--surface); border: var(--bd); border-radius: 6px; overflow: hidden;">
      <app-payslip-header [lang]="lang"></app-payslip-header>

      <div class="grid g-3" style="gap: 0; border-bottom: var(--bd-soft);">
        @for (row of infoRows; track $index; let i = $index) {
          <div style="padding: 10px 16px; border-bottom: var(--bd-soft);"
               [style.border-right]="(i + 1) % 3 !== 0 ? 'var(--bd-soft)' : 'none'">
            <div style="font-size: 10px; color: var(--ink-3); letter-spacing: 0.08em; text-transform: uppercase; font-weight: 700;">
              @if (useEN) { <span>{{ row[0] }}</span> }
              @if (useEN && useML) { <span class="ml" style="font-weight: 600; color: var(--ink-mute);"> · {{ row[2] }}</span> }
              @if (!useEN) { <span class="ml">{{ row[2] }}</span> }
            </div>
            <div style="font-size: 13px; font-weight: 600; margin-top: 2px;">{{ row[1] }}</div>
          </div>
        }
      </div>

      <div class="grid g-3" style="gap: 0; border-bottom: var(--bd-soft);">
        @for (row of daysRows; track $index; let i = $index) {
          <div style="padding: 10px 16px; text-align: center;"
               [style.border-right]="i < 2 ? 'var(--bd-soft)' : 'none'">
            <div style="font-size: 10px; color: var(--ink-3); letter-spacing: 0.08em; text-transform: uppercase; font-weight: 700;">
              @if (useEN) { <span>{{ row[0] }}</span> }
              @if (useEN && useML) { <span class="ml"> · {{ row[2] }}</span> }
              @if (!useEN) { <span class="ml">{{ row[2] }}</span> }
            </div>
            <div class="mono" style="font-size: 22px; font-weight: 700; margin-top: 2px;">{{ row[1] }}</div>
          </div>
        }
      </div>

      <div class="grid g-2" style="gap: 0;">
        <div style="border-right: var(--bd);">
          <div style="padding: 10px 16px; background: var(--leaf-soft); border-bottom: var(--bd-soft); font-weight: 700; font-size: 12px; text-transform: uppercase; letter-spacing: 0.06em;">
            @if (useEN) { <span>Earnings</span> }
            @if (useEN && useML) { <span> · </span> }
            @if (useML) { <span class="ml">വരവ്</span> }
          </div>
          <table class="tbl dense" style="width: 100%;">
            <tbody>
              @for (r of p.earnings; track r.code) {
                <tr>
                  <td style="padding-left: 16px;">
                    @if (useEN) { <b style="font-size: 12px;">{{ r.desc }}</b> }
                    @if (useEN && useML) { <div class="ml muted" style="font-size: 11px;">{{ r.desc_ml }}</div> }
                    @if (!useEN) { <div class="ml" style="font-size: 13px;">{{ r.desc_ml }}</div> }
                  </td>
                  <td class="num" style="padding-right: 16px;"><b class="mono">₹{{ r.amount.toLocaleString('en-IN') }}</b></td>
                </tr>
              }
              <tr style="background: var(--bg-2);">
                <td style="padding-left: 16px; font-weight: 800;">
                  @if (useEN) { <span>Gross earnings</span> }
                  @if (useML) { <span class="ml">{{ useEN ? ' · ' : '' }}മൊത്തം വരവ്</span> }
                </td>
                <td class="num" style="padding-right: 16px; font-weight: 800;"><b class="mono">₹{{ earningsTotal.toLocaleString('en-IN') }}</b></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div>
          <div style="padding: 10px 16px; background: var(--oxide-soft); border-bottom: var(--bd-soft); font-weight: 700; font-size: 12px; text-transform: uppercase; letter-spacing: 0.06em;">
            @if (useEN) { <span>Deductions</span> }
            @if (useEN && useML) { <span> · </span> }
            @if (useML) { <span class="ml">കിഴിവുകൾ</span> }
          </div>
          <table class="tbl dense" style="width: 100%;">
            <tbody>
              @for (r of p.deductions; track r.code) {
                <tr>
                  <td style="padding-left: 16px;">
                    @if (useEN) { <b style="font-size: 12px;">{{ r.desc }}</b> }
                    @if (useEN && useML) { <div class="ml muted" style="font-size: 11px;">{{ r.desc_ml }}</div> }
                    @if (!useEN) { <div class="ml" style="font-size: 13px;">{{ r.desc_ml }}</div> }
                  </td>
                  <td class="num" style="padding-right: 16px;"><b class="mono">₹{{ r.amount.toLocaleString('en-IN') }}</b></td>
                </tr>
              }
              <tr style="background: var(--bg-2);">
                <td style="padding-left: 16px; font-weight: 800;">
                  @if (useEN) { <span>Total deductions</span> }
                  @if (useML) { <span class="ml">{{ useEN ? ' · ' : '' }}മൊത്തം കിഴിവുകൾ</span> }
                </td>
                <td class="num" style="padding-right: 16px; font-weight: 800;"><b class="mono">₹{{ dedTotal.toLocaleString('en-IN') }}</b></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div style="padding: 18px 24px; background: var(--ink); color: var(--bg);">
        <div class="row between" style="align-items: flex-end;">
          <div>
            <div style="font-size: 11px; opacity: 0.7; letter-spacing: 0.1em; text-transform: uppercase; font-weight: 700;">
              @if (useEN) { <span>Net pay </span> }
              @if (useML) { <span class="ml">· അറ്റ വേതനം</span> }
            </div>
            <div class="mono" style="font-size: 30px; font-weight: 800; letter-spacing: -0.02em;">₹{{ net.toLocaleString('en-IN') }}.00</div>
            <div class="muted" style="font-size: 11px; color: var(--bg-3);">
              @if (useEN) { <span>Rupees Twenty four thousand five hundred thirty two only</span><br/> }
              @if (useML) { <span class="ml">ഇരുപത്തിനാലായിരത്തി അഞ്ഞൂറ്റി മുപ്പത്തിരണ്ട് രൂപ മാത്രം</span> }
            </div>
          </div>
          <div style="text-align: right; font-size: 11px; color: var(--bg-3); font-family: var(--font-mono);">
            UTR · KSBNEFT/2026/05/8432104<br/>
            NEFT credit · 31-May-2026<br/>
            Slip ref · SLP-KLP-1042-202605
          </div>
        </div>
      </div>

      <div style="padding: 12px 24px; font-size: 10px; color: var(--ink-3); display: flex; justify-content: space-between;">
        <span>System-generated, signature not required. For queries, contact Estate Manager.</span>
        <span class="mono">Page 1 of 1</span>
      </div>
    </div>
  `
})
export class PayslipAComponent {
  @Input() lang = 'both';
  dataService = inject(DataService);
  
  get p(): any { return this.dataService.payslip; }
  get useML() { return this.lang !== 'en'; }
  get useEN() { return this.lang !== 'ml'; }
  
  get earningsTotal(): number { return this.p.earnings.reduce((s: number, r: any) => s + r.amount, 0); }
  get dedTotal(): number { return this.p.deductions.reduce((s: number, r: any) => s + r.amount, 0); }
  get net(): number { return this.earningsTotal - this.dedTotal; }

  get infoRows() {
    return [
      ['Employee No.', 'EMP-1042', 'തൊഴിലാളി നം.'],
      ['Name',         this.p.emp.name, 'പേര്'],
      ['Category',     'Permanent · T2', 'വിഭാഗം'],
      ['Block / Role', 'KLP-B07 · Tapper', 'ബ്ലോക്ക് / റോൾ'],
      ['Pay period',   this.p.period, 'വേതന കാലയളവ്'],
      ['Bank A/c',     this.p.emp.acct, 'ബാങ്ക് അക്കൗണ്ട്'],
    ];
  }

  get daysRows() {
    return [
      ['Days worked', this.p.days_worked, 'പ്രവൃത്തി ദിവസം'],
      ['Present',     this.p.days_present, 'ഹാജർ'],
      ['Leave',       this.p.days_leave, 'അവധി'],
    ];
  }
}
