import { Component, Input, computed, inject } from '@angular/core';
import { AppConfigService } from '../../../core/services/app-config.service';

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    operations: 'Operations', masters: 'Masters', finance: 'Finance', insight: 'Insight', system: 'System',
    dashboard: 'Dashboard', attendance: 'Attendance', dps: 'Daily Production', collection: 'Collection Centre',
    tapping: 'Tapping Schedule', workers: 'Workers', assets: 'Estate & Blocks', inventory: 'Inventory',
    mazdoor: 'Mazdoor Estimate', payroll: 'Payroll', payslip: 'Payslip', reports: 'Reports', settings: 'Settings',
    field: 'Field App', search_p: 'Search workers, blocks, vouchers…', today: 'Today', yesterday: 'Yesterday',
    export_pdf: 'Export PDF', new_block: 'New block', estates_kpi: 'Estates', blocks_kpi: 'Blocks',
    tree_census: 'Tree census', replant_queue: 'Replant queue', mature: 'Mature', immature: 'Immature',
    cut: 'CUT', slaughter: 'Slaughter', divisions: 'Divisions', block_id: 'Block ID', block_name: 'Block name',
    division: 'Division', hectares: 'Hect.', trees: 'Trees', variety: 'Variety', planted: 'Planted',
    maturity: 'Maturity', cycle: 'Cycle', tappers: 'Tappers', yield_ha: 'Yield/ha',
    wk_perm: 'Permanent', wk_cas: 'Casual', wk_dep: 'Dependent', wk_tot: 'Total',
    workers_unit: 'workers', retiring_q: 'retiring this quarter',
    added_m: 'added this month', awaiting_doc: 'awaiting documents',
    utilization_today: 'utilisation today', quick_mark: 'Quick mark',
    search_emp: 'Scan ID / type EMP-...', all_cats: 'All categories',
    all_roles: 'All roles', all_blocks: 'All blocks', more_filters: 'More filters',
    showing: 'Showing', of: 'of', page: 'Page', prev: 'Prev', next: 'Next',
    emp_id: 'EMP ID', name: 'Name', category: 'Category', role: 'Role',
    block: 'Block', joined: 'Joined', bank_acct: 'Bank Account',
    aadhaar: 'Aadhaar', day_rate: 'Day rate', org_hierarchy: 'Employee hierarchy',
    import_csv: 'Import CSV', new_worker: 'New worker',
    assets_sub: 'Land, divisions, blocks, tree census, maturity status',
    hectares_total: 'hectares total', mature_stats: 'mature ·', immature_stats: 'immature ·', cut_stats: 'CUT/slaughter',
    last_verified: 'last verified Mar 2026', fy_plan: 'FY26-27 plan',
    manager: 'Manager', address: 'Address', estate: 'Estate',
    inv_sub: 'Ammonia, fertilizers, latex cups, tools · across 5 estates',
    stock_report: 'Stock report (PDF)', grn: 'GRN', issue_voucher: 'Issue voucher',
    stock_register: 'Stock register', todays_issues: 'Today\'s issues',
    sku: 'SKU', item: 'Item', stock: 'Stock', uom: 'UoM', reorder: 'Re-order', location: 'Location', unit_rs: 'Unit ₹', value: 'Value', status: 'Status',
    voucher: 'Voucher', to: 'To', qty: 'Qty',
    skus_tracked: 'SKUs tracked', inv_value: 'Inventory value', issued_week: 'Issued this week', stockouts: 'Stock-out events',
    mzd_sub: 'Non-tapping task budgeting · authorisations · live consumption',
    new_estimate: 'New estimate',
    open_estimates: 'Open estimates', sanctioned_budget: 'Sanctioned budget', consumed: 'Consumed', pending_approval: 'Pending approval',
    active_estimates: 'Active estimates', est_no: 'Est. No.', task: 'Task', mandays: 'Mandays sanctioned', used: 'Used', burn: 'Burn', budget: 'Budget',
    create_estimate: 'Create new estimate', day_rate_mzd: 'Day rate', est_cost: 'Estimated cost', start_date: 'Start date', notes: 'Notes',
    att_sub: 'Block-wise daily attendance · Muster Sheet No. 9201',
    bio_sync: 'Biometric sync', close_muster: 'Close muster',
    date: 'Date', filter: 'Filter',
    present: 'Present', absent: 'Absent', leave: 'Leave',
    muster_roll: 'Muster Roll', field_supervisor: 'Field Supervisor',
    worker: 'Worker', cat: 'Cat.', status_att: 'Status', in_time: 'In', out_time: 'Out', hours: 'Hours', remarks: 'Remarks',
    p_present: 'P · Present', a_absent: 'A · Absent', l_leave: 'L · Leave',
    dps_title: 'Daily Production Statement', dps_sub: 'DPS-9201 · Latex & scrap collection per tapper · 25 May 2026',
    supervisor: 'Supervisor', bulk_import: 'Bulk import', print_sheet: 'Print sheet', verify_submit: 'Verify & submit',
    trees_in_block: 'Trees in block', expected_yield: 'Expected yield', base_drc: 'Base DRC',
    tapper: 'Tapper', trees_tapped: 'Trees Tapped', cups_recovered: 'Cups Recovered', latex_l: 'Latex (L)', wt_kg: 'Wt (kg)', scrap_kg: 'Scrap (kg)', drc_pct: 'DRC %', dry_kg: 'Dry kg', base: 'Base',
    verified: 'Verified', pending: 'Pending', totals: 'TOTALS',
    view: 'View', card: 'Card', table: 'Table', add_entry: 'Add entry',
    dry_kg_inc: 'DRY KG · INCENTIVE', verified_by: 'Verified by V. Raj', awaiting_ver: 'Awaiting verification',
    trees_tapped_lbl: 'Trees tapped', cups_recovered_lbl: 'Cups recovered', latex_wt_lbl: 'Latex weight (kg)', scrap_rb_lbl: 'Scrap rubber (kg)', drc_pct_lbl: 'DRC % (lab/field test)', hd_dist_lbl: 'Head-load distance (m)',
    field_remarks: 'Field remarks', save_next: 'Save & next tapper',
    sample_collected: 'Latex sample collected for DRC verification at CC-Main',
    auto_calc: 'Auto-calculated', dry_yield: 'Dry yield', base_yield: 'Base yield', drc_inc: 'DRC incentive', hl_charge: 'Head-load charge', today_earn: 'Today\'s earnings', mtd_dry: 'MTD dry rubber',
    last_14: 'Last 14 days',
    cc_sub: 'CC-Main · Kulathupuzha · Intake, weighing, DRC sampling',
    print_intake: 'Print intake', new_intake: 'New intake',
    intake_log: 'Intake log · today', all: 'All', auto: 'Auto', manual: 'Manual', disputed: 'Disputed',
    time: 'Time', batch: 'Batch', from_block: 'From block', gross_kg: 'Gross (kg)', net_kg: 'Net (kg)', dry: 'Dry',
    drc_test: 'DRC test · live', sample_id: 'Sample ID', method: 'Method', latex_wt: 'Latex wt', sample: 'Sample', coagulum_dry: 'Coagulum dry',
    recommend_fresh: 'Recommend: collect fresh sample · check coagulation time · verify with lab oven-dry method.',
    record_flag: 'Record & flag for retest', block_contrib: 'Block contribution',
    today_intake: 'Today intake', kg_wet: 'kg wet', batches_desc: '42 batches · 6 still to come',
    avg_drc: 'Avg DRC', pct: '%', samples_flagged: '5 samples flagged for retest',
    dry_equiv: 'Dry equivalent', kg: 'kg', lot_sfck: 'lot SFCK/KLP/2026/0512',
    scrap_rubber: 'Scrap rubber', awaiting_grading: 'awaiting grading',
    tap_sub: 'D1–D4 rotation cycle · Kulathupuzha Estate · May 2026',
    recalculate: 'Recalculate', print_roster: 'Print roster', reassign_tapper: 'Reassign tapper',
    reassign_modal: 'Reassign Block Cycle', select_block: 'Select Block', target_cycle: 'Target Cycle Day', cancel: 'Cancel', reassign: 'Reassign',
    blocks_sm: 'blocks', trees_sm: 'trees', supervisors: 'Supervisors:',
    calendar_rot: 'Calendar · D1–D4 rotation for May', rain_holiday: 'Rain holiday',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    no_tapping: 'no tapping', today_upper: 'TODAY',
    d1_assignments: 'D1 assignments · today (active)', tapping_sup: 'Tapping Sup.', start_time: 'Start time', exp_dry: 'Expected dry',
    in_progress: 'In progress', delayed_start: 'Delayed start',
    dash_title: 'Dashboard', dash_sub: 'Monday · 25 May 2026 · 09:42 IST · Cycle Day 26 of 31',
    tweaks: 'Tweaks', refresh: 'Refresh', new_dps: 'New DPS', save_changes: 'Save Changes',
    estate_production: 'Estate production · last 7 days', estate_sub: 'Latex (dry kg) + Scrap rubber. Dashed line = base yield 8,200 kg.',
    latex: 'Latex', scrap: 'Scrap',
    today_by_cycle: 'Today by cycle', d4_in_progress: 'D4 in progress',
    tappers_attention: 'Tappers needing attention', view_all: 'View all',
    issue: 'Issue', vs_base: 'Δ vs base',
    approvals_queue: 'Approvals queue', pending_badge: '14 pending', review: 'Review',
    estate_map: 'Kulathupuzha Estate · block map', cut_slaughter: 'CUT/Slaughter',
    kallada_river: 'KALLADA RIVER', cc_main_map: 'Collection Centre · Kulathupuzha Main', live_ops_feed: 'Live ops feed',
    estate_perf: 'Estate-wise performance · MTD', plan_kg: 'Plan kg', actual: 'Actual', delta_pct: 'Δ%', trend: 'Trend', wage_kg: 'Wage/kg',
    strategic_alerts: 'Strategic alerts',
    my_account: 'My Account', net_pay_cycle: 'Net pay · this cycle', neft_credit: 'NEFT credit · 31 May 2026',
    download_payslip: 'Download payslip', view_detail: 'View detail',
    cycle_so_far: 'This cycle so far · 21 Apr → 25 May',
    days_present: 'Days present', latex_dry: 'Latex dry', delta_base_yield: 'Δ Base yield', drc_avg: 'DRC avg',
    head_load: 'Head-load', incentive_earned: 'Incentive earned', leave_balance: 'Leave balance', coop_balance: 'Co-op balance',
    my_daily_prod: 'My daily production · last 14 days', my_dry_kg: 'My dry kg', base_105: 'Base 10.5 kg',
    my_recent_days: 'My recent days',
    view_payslip_card: 'View payslip', apply_leave: 'Apply for leave', coop_society: 'Co-op society', my_bank_details: 'My bank details',
    en_ml_mobile: 'EN · ML · Mobile', cl_el_sick: 'CL · EL · Sick', coop_bal_rs: 'Balance ₹4,200', acct: 'A/c',
    notices_office: 'Notices from estate office',
    wages: 'WAGES', medical: 'MEDICAL', rain: 'RAIN',
    notice1_title: 'DA hike of ₹186/day applicable from 29-Apr-2026', notice1_desc: 'Per GO(Rt) 412/2026/Lab. Mid-cycle rate auto-prorated in this payslip.',
    notice2_title: 'Free health camp · 02 June 2026 · Kulathupuzha Estate clinic', notice2_desc: 'All workers and dependents eligible. Report 08:00 to 14:00.',
    notice3_title: 'Monsoon rainguarding starts 10 June', notice3_desc: 'Apply rainguard polythene strips before south-west monsoon. Field supervisor will instruct.',
    my_day: 'My Day', sys_overview: 'System Overview', audit_workspace: 'Audit Workspace', my_day_cc: 'My Day · Collection Centre',
    sys_sub: 'Service health · users · integrations · audit',
    open_settings: 'Open settings', export_findings: 'Export findings', raise_finding: 'Raise finding',
    good_morning: 'Good morning', tappers_today: 'Tappers · today', latex_collected: 'Latex collected', pending_verify: 'Pending verify',
    blocks_18_msg: '18 blocks · D1 cycle today · 412 tappers in rotation', blocks_3_msg: '3 blocks · D1 cycle today · 38 tappers under you',
    open_muster: 'Open muster', add_dps_entry: 'Add DPS entry', record_intake: 'Record intake', issue_ammonia: 'Issue ammonia',
    klp_b07_d1: 'KLP-B07 · D1', pending_verification_9: '9 pending verification', cc_main_6_batches: 'CC-Main · 6 batches due', blocks_awaiting_2: '2 blocks awaiting',
    my_blocks_today_d1: 'My blocks · today (D1 cycle)', on_track: 'On track', drc_low: 'DRC low', open_dps: 'Open DPS',
    todo_4_items: 'To-do · 4 items', open: 'Open',
    verify_9_dps: 'Verify 9 DPS entries', submitted_by_v_raj: 'Submitted by V. Raj · 09:32',
    mark_suresh_absent: 'Mark Suresh Babu absent (3rd day)', auto_escalate_field_officer: 'Auto-escalate to Field Officer',
    sample_retest_saritha: 'Sample retest · Saritha Anand', drc_flagged_cc: 'DRC 31.4% flagged at CC',
    submit_estimate_est: 'Submit Estimate EST-1042', plus_12_mandays: '+12 mandays · clearing B19',
    cc_dash_batches_done: 'Batches done', cc_dash_retests_due: 'Retests due',
    cc_dash_weigh_drc_sample: 'Weigh - DRC sample', cc_dash_open_intake_queue: 'Open intake queue',
    cc_dash_batches_awaiting: '6 batches awaiting', cc_dash_blocks_requested: '2 blocks requested',
    cc_dash_my_muster: 'My muster', cc_dash_mark_present: 'Mark present 07:00',
    cc_dash_last_8_intakes: 'Last 8 intakes · awaiting tag', cc_dash_cc_stock_at_hand: 'CC stock at hand',
    cc_dash_full_inventory: 'Full inventory →',
    payroll_sub: 'Cycle 21 Apr – 20 May 2026 · 21st-to-20th roll · 1,623 workers',
    recompute: 'Recompute', bank_file_neft: 'Bank file (NEFT)', close_cycle: 'Close cycle',
    gross_wages: 'Gross wages', lakh: 'lakh', gross_wages_sub: '21 Apr – 20 May · 1,623 workers',
    avg_wage_worker: 'Avg wage / worker', da_hike_applied: '▲ ₹186 (DA hike applied)',
    drc_incentive_pool: 'DRC incentive pool', tappers_above_base: '412 tappers above base',
    variance_flags: 'Variance flags', needs_review_before_close: 'needs review before close',
    collect_inputs: 'Collect inputs', collect_inputs_sub: 'Attendance + DPS + Mazdoor',
    compute_wages: 'Compute wages', compute_wages_sub: 'Slabs · DA · incentives',
    review_variances: 'Review variances', review_variances_sub: '12 anomalies flagged',
    approval_ladder: 'Approval ladder', approval_ladder_sub: 'EM → GM → MD',
    disburse: 'Disburse', disburse_sub: 'NEFT batch to KSB',
    payslip_release: 'Payslip release', payslip_release_sub: 'EN + ML PDFs · SMS link',
    wage_variance_needs_review: 'Wage variance · needs review', flags_12: '12 flags',
    worker_lbl: 'Worker', last_cycle: 'Last cycle', this_cycle: 'This cycle', delta: 'Δ', reason: 'Reason',
    drc_inc_up: 'DRC incentive ▲', days_3_absent: '3 days absent', ot_12_hrs: 'OT 12 hrs', drc_hl_up: 'DRC + head-load ▲', low_drc_pen: 'Low DRC penalty',
    comp_gross_wages: 'Composition of gross wages · ₹68.4 lakh', basic_wages: 'Basic wages', da: 'Dearness Allowance (DA)',
    hra: 'House Rent Allowance', hl_slab: 'Head-load charge (slab-based)', drc_yield_inc: 'DRC / yield incentive', overtime: 'Overtime',
    mid_cycle_da_applied: 'Mid-cycle DA hike applied: ₹186/worker × 1,623 = ₹3,01,878',
    mid_cycle_da_sub: 'Per GO(Rt) No. 412/2026/Lab. dated 28-Apr-2026. Auto-prorated 21-Apr to 28-Apr at old rate, 29-Apr onward at new rate.',
    cycle_preview: 'Cycle preview · all workers',
    days_lbl: 'Days', basic_lbl: 'Basic', da_lbl: 'DA', hl_lbl: 'HL', incentive_lbl: 'Incentive', gross_lbl: 'Gross', deduct_lbl: 'Deduct', net_lbl: 'Net',
    review_badge: 'Review', ok_badge: 'OK', showing_8_of: 'Showing 8 of 1,623 · totals at bottom of cycle report',
    view_full_register: 'View full register', submit_for_approval: 'Submit for approval',
    payslip_sub: 'Rajan Pillai · EMP-1042 · Cycle 21 Apr – 20 May 2026',
    pdf_en: 'PDF (EN)', pdf_ml: 'PDF (ML)', download_pdf: 'Download PDF', sms_to_worker: 'SMS to worker',
    variant: 'Variant', official: 'Official', malayalam: 'Malayalam', mobile_sms: 'Mobile/SMS'
  },
  ml: {
    operations: 'പ്രവർത്തനങ്ങൾ', masters: 'മാസ്റ്ററുകൾ', finance: 'ധനകാര്യം', insight: 'വിശകലനം', system: 'സിസ്റ്റം',
    dashboard: 'ഡാഷ്ബോർഡ്', attendance: 'ഹാജർ', dps: 'ദൈനംദിന ഉൽപാദനം', collection: 'കളക്ഷൻ കേന്ദ്രം',
    tapping: 'ടാപ്പിംഗ് ഷെഡ്യൂൾ', workers: 'തൊഴിലാളികൾ', assets: 'എസ്റ്റേറ്റ് & ബ്ലോക്കുകൾ', inventory: 'ഇൻവെന്ററി',
    mazdoor: 'മസ്ദൂർ എസ്റ്റിമേറ്റ്', payroll: 'വേതനം', payslip: 'പേസ്ലിപ്പ്', reports: 'റിപ്പോർട്ടുകൾ', settings: 'ക്രമീകരണങ്ങൾ',
    field: 'ഫീൽഡ് ആപ്പ്', search_p: 'തൊഴിലാളികൾ, ബ്ലോക്കുകൾ തിരയുക…', today: 'ഇന്ന്', yesterday: 'ഇന്നലെ',
    export_pdf: 'PDF ഡൗൺലോഡ്', new_block: 'പുതിയ ബ്ലോക്ക്', estates_kpi: 'എസ്റ്റേറ്റുകൾ', blocks_kpi: 'ബ്ലോക്കുകൾ',
    tree_census: 'മരങ്ങളുടെ സെൻസസ്', replant_queue: 'റീപ്ലാന്റ് ക്യൂ', mature: 'ടാപ്പിംഗ്', immature: 'വളരുന്നവ',
    cut: 'വെട്ടിയവ', slaughter: 'സ്ലോട്ടർ', divisions: 'ഡിവിഷനുകൾ', block_id: 'ബ്ലോക്ക് ID', block_name: 'ബ്ലോക്ക് പേര്',
    division: 'ഡിവിഷൻ', hectares: 'ഹെക്ടർ', trees: 'മരങ്ങൾ', variety: 'ഇനം', planted: 'നട്ട വർഷം',
    maturity: 'വളർച്ച', cycle: 'സൈക്കിൾ', tappers: 'ടാപ്പർമാർ', yield_ha: 'ഉൽപാദനം/ഹെ.',
    wk_perm: 'സ്ഥിരം', wk_cas: 'താൽക്കാലികം', wk_dep: 'ആശ്രിതർ', wk_tot: 'ആകെ',
    workers_unit: 'തൊഴിലാളികൾ', retiring_q: 'ഈ പാദത്തിൽ വിരമിക്കുന്നവർ',
    added_m: 'ഈ മാസം ചേർന്നവർ', awaiting_doc: 'രേഖകൾ പ്രതീക്ഷിക്കുന്നു',
    utilization_today: 'ഇന്നത്തെ ഉപയോഗം', quick_mark: 'വേഗത്തിൽ അടയാളപ്പെടുത്തുക',
    search_emp: 'ഐഡി സ്കാൻ ചെയ്യുക / EMP-... ടൈപ്പ് ചെയ്യുക', all_cats: 'എല്ലാ വിഭാഗങ്ങളും',
    all_roles: 'എല്ലാ റോളുകളും', all_blocks: 'എല്ലാ ബ്ലോക്കുകളും', more_filters: 'കൂടുതൽ ഫിൽറ്ററുകൾ',
    showing: 'കാണിക്കുന്നത്', of: 'ൽ', page: 'പേജ്', prev: 'മുമ്പത്തെ', next: 'അടുത്തത്',
    emp_id: 'എംപ്ലോയി ഐഡി', name: 'പേര്', category: 'വിഭാഗം', role: 'റോൾ',
    block: 'ബ്ലോക്ക്', joined: 'ചേർന്ന തീയതി', bank_acct: 'ബാങ്ക് അക്കൗണ്ട്',
    aadhaar: 'ആധാർ', day_rate: 'ദിവസ വേതനം', org_hierarchy: 'തൊഴിലാളി ശ്രേണി',
    import_csv: 'CSV ഇമ്പോർട്ട് ചെയ്യുക', new_worker: 'പുതിയ തൊഴിലാളി',
    assets_sub: 'ഭൂമി, ഡിവിഷനുകൾ, ബ്ലോക്കുകൾ, മരങ്ങളുടെ സെൻസസ്, വളർച്ചാ നില',
    hectares_total: 'ഹെക്ടർ ആകെ', mature_stats: 'ടാപ്പിംഗ് ·', immature_stats: 'വളരുന്നവ ·', cut_stats: 'വെട്ടിയവ/സ്ലോട്ടർ',
    last_verified: 'അവസാന പരിശോധന Mar 2026', fy_plan: 'FY26-27 പദ്ധതി',
    manager: 'മാനേജർ', address: 'വിലാസം', estate: 'എസ്റ്റേറ്റ്',
    inv_sub: 'അമോണിയ, വളം, കപ്പുകൾ, ഉപകരണങ്ങൾ · 5 എസ്റ്റേറ്റുകളിൽ',
    stock_report: 'സ്റ്റോക്ക് റിപ്പോർട്ട് (PDF)', grn: 'GRN', issue_voucher: 'ഇഷ്യൂ വൗച്ചർ',
    stock_register: 'സ്റ്റോക്ക് രജിസ്റ്റർ', todays_issues: 'ഇന്നത്തെ ഇഷ്യൂകൾ',
    sku: 'SKU', item: 'സാധനം', stock: 'സ്റ്റോക്ക്', uom: 'UoM', reorder: 'റീ-ഓർഡർ', location: 'സ്ഥലം', unit_rs: 'വില ₹', value: 'മൂല്യം', status: 'അവസ്ഥ',
    voucher: 'വൗച്ചർ', to: 'ലേക്ക്', qty: 'അളവ്',
    skus_tracked: 'SKU ട്രാക്ക് ചെയ്യുന്നു', inv_value: 'ഇൻവെന്ററി മൂല്യം', issued_week: 'ഈ ആഴ്ച നൽകിയത്', stockouts: 'സ്റ്റോക്ക് ഇല്ലാത്തവ',
    mzd_sub: 'ടാപ്പിംഗ് ഇതര ബഡ്ജറ്റിംഗ് · അനുമതികൾ · ഉപയോഗം',
    new_estimate: 'പുതിയ എസ്റ്റിമേറ്റ്',
    open_estimates: 'തുറന്ന എസ്റ്റിമേറ്റുകൾ', sanctioned_budget: 'അനുവദിച്ച ബഡ്ജറ്റ്', consumed: 'ഉപയോഗിച്ചത്', pending_approval: 'അനുമതി കാത്തിരിക്കുന്നു',
    active_estimates: 'സജീവ എസ്റ്റിമേറ്റുകൾ', est_no: 'എസ്റ്റിമേറ്റ് നമ്പർ', task: 'ജോലി', mandays: 'അനുവദിച്ച തൊഴിൽ ദിനങ്ങൾ', used: 'ഉപയോഗിച്ചത്', burn: 'ബേൺ', budget: 'ബഡ്ജറ്റ്',
    create_estimate: 'പുതിയ എസ്റ്റിമേറ്റ് ഉണ്ടാക്കുക', day_rate_mzd: 'ദിവസ വേതനം', est_cost: 'കണക്കാക്കിയ ചിലവ്', start_date: 'തുടങ്ങുന്ന തീയതി', notes: 'കുറിപ്പുകൾ',
    att_sub: 'ബ്ലോക്ക് തിരിച്ചുള്ള ഹാജർ · മാസ്റ്റർ ഷീറ്റ് നം. 9201',
    bio_sync: 'ബയോമെട്രിക് സിങ്ക്', close_muster: 'മാസ്റ്റർ ക്ലോസ് ചെയ്യുക',
    date: 'തീയതി', filter: 'ഫിൽറ്റർ ചെയ്യുക',
    present: 'ഹാജർ', absent: 'അില്ല', leave: 'അവധി',
    muster_roll: 'മാസ്റ്റർ റോൾ', field_supervisor: 'ഫീൽഡ് സൂപ്പർവൈസർ',
    worker: 'തൊഴിലാളി', cat: 'വിഭാഗം', status_att: 'അവസ്ഥ', in_time: 'വന്നത്', out_time: 'പോയത്', hours: 'മണിക്കൂർ', remarks: 'കുറിപ്പുകൾ',
    p_present: 'P · ഹാജർ', a_absent: 'A · അില്ല', l_leave: 'L · അവധി',
    dps_title: 'ദൈനംദിന ഉൽപാദന സ്റ്റേറ്റ്മെൻ്റ്', dps_sub: 'DPS-9201 · ഓരോ ടാപ്പർക്കും ലഭിച്ച ലാറ്റക്സ് & സ്ക്രാപ്പ് · 25 മെയ് 2026',
    supervisor: 'സൂപ്പർവൈസർ', bulk_import: 'ബൾക്ക് ഇമ്പോർട്ട്', print_sheet: 'ഷീറ്റ് പ്രിൻ്റ് ചെയ്യുക', verify_submit: 'ഉറപ്പാക്കി സമർപ്പിക്കുക',
    trees_in_block: 'ബ്ലോക്കിലെ മരങ്ങൾ', expected_yield: 'പ്രതീക്ഷിക്കുന്ന ഉൽപാദനം', base_drc: 'അടിസ്ഥാന DRC',
    tapper: 'ടാപ്പർ', trees_tapped: 'ടാപ്പ് ചെയ്ത മരങ്ങൾ', cups_recovered: 'ലഭിച്ച കപ്പുകൾ', latex_l: 'ലാറ്റക്സ് (L)', wt_kg: 'ഭാരം (kg)', scrap_kg: 'സ്ക്രാപ്പ് (kg)', drc_pct: 'DRC %', dry_kg: 'ഉണങ്ങിയ kg',
    verified: 'ഉറപ്പാക്കി', pending: 'പെൻഡിംഗ്', totals: 'ആകെ',
    view: 'കാണുക', card: 'കാർഡ്', table: 'പട്ടിക', add_entry: 'എൻട്രി ചേർക്കുക',
    dry_kg_inc: 'ഉണങ്ങിയ KG · ഇൻസെൻ്റീവ്', verified_by: 'ഉറപ്പാക്കിയത് V. രാജ്', awaiting_ver: 'ഉറപ്പാക്കാൻ കാത്തിരിക്കുന്നു',
    trees_tapped_lbl: 'ടാപ്പ് ചെയ്ത മരങ്ങൾ', cups_recovered_lbl: 'ലഭിച്ച കപ്പുകൾ', latex_wt_lbl: 'ലാറ്റക്സ് ഭാരം (kg)', scrap_rb_lbl: 'സ്ക്രാപ്പ് റബ്ബർ (kg)', drc_pct_lbl: 'DRC % (ലാബ്/ഫീൽഡ് പരിശോധന)', hd_dist_lbl: 'ചുമക്കുന്ന ദൂരം (m)',
    field_remarks: 'ഫീൽഡ് കുറിപ്പുകൾ', save_next: 'സേവ് ചെയ്യുക & അടുത്ത ടാപ്പർ',
    sample_collected: 'DRC പരിശോധനയ്ക്കായി ലാറ്റക്സ് സാമ്പിൾ CC-Main ൽ ശേഖരിച്ചു',
    auto_calc: 'ഓട്ടോ-കണക്കാക്കിയത്', dry_yield: 'ഉണങ്ങിയ ഉൽപാദനം', base_yield: 'അടിസ്ഥാന ഉൽപാദനം', drc_inc: 'DRC ഇൻസെൻ്റീവ്', hl_charge: 'ചുമട്ടു കൂലി', today_earn: 'ഇന്നത്തെ വരുമാനം', mtd_dry: 'ഈ മാസം ഉണങ്ങിയത്',
    last_14: 'കഴിഞ്ഞ 14 ദിവസങ്ങൾ',
    cc_sub: 'CC-Main · കുളത്തൂപ്പുഴ · ശേഖരണം, തൂക്കം, DRC സാമ്പിളിംഗ്',
    print_intake: 'ഇൻടേക്ക് പ്രിൻ്റ് ചെയ്യുക', new_intake: 'പുതിയ ഇൻടേക്ക്',
    intake_log: 'ഇൻടേക്ക് ലോഗ് · ഇന്ന്', all: 'എല്ലാം', auto: 'ഓട്ടോ', manual: 'മാനുവൽ', disputed: 'തർക്കമുള്ളവ',
    time: 'സമയം', batch: 'ബാച്ച്', from_block: 'ബ്ലോക്കിൽ നിന്ന്', gross_kg: 'മൊത്തം (kg)', net_kg: 'അറ്റ ഭാരം (kg)', dry: 'ഉണങ്ങിയത്',
    drc_test: 'DRC പരിശോധന · ലൈവ്', sample_id: 'സാമ്പിൾ ഐഡി', method: 'രീതി', latex_wt: 'ലാറ്റക്സ് ഭാരം', sample: 'സാമ്പിൾ', coagulum_dry: 'ഉണങ്ങിയ കൊയാഗുലം',
    recommend_fresh: 'നിർദ്ദേശം: പുതിയ സാമ്പിൾ ശേഖരിക്കുക · ഉറയുന്ന സമയം നോക്കുക · ലാബ് ഓവൻ വഴി പരിശോധിക്കുക.',
    record_flag: 'റെക്കോർഡ് ചെയ്ത് വീണ്ടും പരിശോധിക്കാൻ ഫ്ലാഗ് ചെയ്യുക', block_contrib: 'ബ്ലോക്കിന്റെ സംഭാവന',
    today_intake: 'ഇന്നത്തെ ഇൻടേക്ക്', kg_wet: 'kg നനഞ്ഞത്', batches_desc: '42 ബാച്ചുകൾ · 6 എണ്ണം വരാനുണ്ട്',
    avg_drc: 'ശരാശരി DRC', pct: '%', samples_flagged: '5 സാമ്പിളുകൾ വീണ്ടും പരിശോധിക്കാൻ ഫ്ലാഗ് ചെയ്തു',
    dry_equiv: 'ഉണങ്ങിയതിന് തുല്യം', kg: 'kg', lot_sfck: 'lot SFCK/KLP/2026/0512',
    scrap_rubber: 'സ്ക്രാപ്പ് റബ്ബർ', awaiting_grading: 'ഗ്രേഡിംഗിനായി കാത്തിരിക്കുന്നു',
    tap_sub: 'D1–D4 റൊട്ടേഷൻ സൈക്കിൾ · കുളത്തൂപ്പുഴ എസ്റ്റേറ്റ് · മെയ് 2026',
    recalculate: 'വീണ്ടും കണക്കാക്കുക', print_roster: 'റോസ്റ്റർ പ്രിൻ്റ് ചെയ്യുക', reassign_tapper: 'ടാപ്പറെ മാറ്റുക',
    reassign_modal: 'ബ്ലോക്ക് സൈക്കിൾ മാറ്റുക', select_block: 'ബ്ലോക്ക് തിരഞ്ഞെടുക്കുക', target_cycle: 'സൈക്കിൾ ദിവസം', cancel: 'റദ്ദാക്കുക', reassign: 'മാറ്റുക',
    blocks_sm: 'ബ്ലോക്കുകൾ', trees_sm: 'മരങ്ങൾ', supervisors: 'സൂപ്പർവൈസർമാർ:',
    calendar_rot: 'കലണ്ടർ · മെയ് മാസത്തെ D1–D4 റൊട്ടേഷൻ', rain_holiday: 'മഴ അവധി',
    mon: 'തിങ്കൾ', tue: 'ചൊവ്വ', wed: 'ബുധൻ', thu: 'വ്യാഴം', fri: 'വെള്ളി', sat: 'ശനി', sun: 'ഞായർ',
    no_tapping: 'ടാപ്പിംഗ് ഇല്ല', today_upper: 'ഇന്ന്',
    d1_assignments: 'D1 ചുമതലകൾ · ഇന്ന് (സജീവം)', tapping_sup: 'ടാപ്പിംഗ് സൂപ്പർവൈസർ', start_time: 'തുടങ്ങുന്ന സമയം', exp_dry: 'പ്രതീക്ഷിക്കുന്ന ഉണങ്ങിയത്',
    in_progress: 'നടക്കുന്നു', delayed_start: 'വൈകി തുടങ്ങി',
    dash_title: 'ഡാഷ്‌ബോർഡ്', dash_sub: 'തിങ്കൾ · 25 മെയ് 2026 · 09:42 IST · സൈക്കിൾ ദിവസം 26 (31 ൽ)',
    tweaks: 'ക്രമീകരണങ്ങൾ', refresh: 'റിഫ്രഷ്', new_dps: 'പുതിയ DPS', save_changes: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    estate_production: 'എസ്റ്റേറ്റ് ഉൽപാദനം · കഴിഞ്ഞ 7 ദിവസങ്ങൾ', estate_sub: 'ലാറ്റക്സ് (ഉണങ്ങിയത് kg) + സ്ക്രാപ്പ് റബ്ബർ. ഡാഷ്ഡ് ലൈൻ = അടിസ്ഥാന ഉൽപാദനം 8,200 kg.',
    latex: 'ലാറ്റക്സ്', scrap: 'സ്ക്രാപ്പ്',
    today_by_cycle: 'സൈക്കിൾ പ്രകാരം ഇന്ന്', d4_in_progress: 'D4 നടക്കുന്നു',
    tappers_attention: 'ശ്രദ്ധിക്കേണ്ട ടാപ്പർമാർ', view_all: 'എല്ലാം കാണുക',
    issue: 'പ്രശ്നം', vs_base: 'Δ അടിസ്ഥാനം മാറ്റം',
    approvals_queue: 'അനുമതിക്കായി കാത്തിരിക്കുന്നവ', pending_badge: '14 പെൻഡിംഗ്', review: 'പരിശോധിക്കുക',
    estate_map: 'കുളത്തൂപ്പുഴ എസ്റ്റേറ്റ് · ബ്ലോക്ക് മാപ്പ്', cut_slaughter: 'വെട്ടിയവ',
    kallada_river: 'കല്ലട നദി', cc_main_map: 'ശേഖരണ കേന്ദ്രം · കുളത്തൂപ്പുഴ', live_ops_feed: 'ലൈവ് പ്രവർത്തനങ്ങൾ',
    estate_perf: 'എസ്റ്റേറ്റ് പ്രകടനം · ഈ മാസം', plan_kg: 'ലക്ഷ്യം kg', actual: 'ലഭിച്ചത്', delta_pct: 'Δ%', trend: 'ട്രെൻഡ്', wage_kg: 'കൂലി/kg',
    strategic_alerts: 'പ്രധാന അറിയിപ്പുകൾ',
    my_account: 'എന്റെ അക്കൗണ്ട്', net_pay_cycle: 'അറ്റ വേതനം', neft_credit: 'NEFT ക്രെഡിറ്റ് · 31 മെയ് 2026',
    download_payslip: 'പേസ്ലിപ്പ് ഡൗൺലോഡ്', view_detail: 'വിശദാംശങ്ങൾ കാണുക',
    cycle_so_far: 'ഈ സൈക്കിൾ ഇതുവരെ · 21 Apr → 25 May',
    days_present: 'ഹാജരായ ദിവസങ്ങൾ', latex_dry: 'ഉണങ്ങിയ ലാറ്റക്സ്', delta_base_yield: 'Δ അടിസ്ഥാന മാറ്റം', drc_avg: 'ശരാശരി DRC',
    head_load: 'ചുമട്', incentive_earned: 'ലഭിച്ച ഇൻസെന്റീവ്', leave_balance: 'അവധി ബാക്കി', coop_balance: 'Co-op ബാക്കി',
    my_daily_prod: 'എന്റെ ദൈനംദിന ഉൽപാദനം · കഴിഞ്ഞ 14 ദിവസങ്ങൾ', my_dry_kg: 'എന്റെ ഉണങ്ങിയ kg', base_105: 'അടിസ്ഥാനം 10.5 kg',
    my_recent_days: 'എന്റെ സമീപകാല ദിവസങ്ങൾ',
    view_payslip_card: 'പേസ്ലിപ്പ് കാണുക', apply_leave: 'അവധിക്കായി അപേക്ഷിക്കുക', coop_society: 'സൊസൈറ്റി', my_bank_details: 'എന്റെ ബാങ്ക് വിവരങ്ങൾ',
    en_ml_mobile: 'EN · ML · മൊബൈൽ', cl_el_sick: 'CL · EL · Sick', coop_bal_rs: 'ബാക്കി ₹4,200', acct: 'A/c',
    notices_office: 'എസ്റ്റേറ്റ് നോട്ടീസ്',
    wages: 'വേതനം', medical: 'മെഡിക്കൽ', rain: 'മഴ',
    notice1_title: '₹186/ദിവസം DA വർദ്ധന 29-Apr-2026 മുതൽ പ്രാബല്യത്തിൽ', notice1_desc: 'GO(Rt) 412/2026/Lab പ്രകാരം. ഈ പേസ്ലിപ്പിൽ മാറ്റം വരുത്തിയിട്ടുണ്ട്.',
    notice2_title: 'സൗജന്യ മെഡിക്കൽ ക്യാമ്പ് · 02 ജൂൺ 2026 · കുളത്തൂപ്പുഴ എസ്റ്റേറ്റ് ക്ലിനിക്ക്', notice2_desc: 'എല്ലാ തൊഴിലാളികൾക്കും ആശ്രിതർക്കും അർഹതയുണ്ട്. 08:00 മുതൽ 14:00 വരെ വരിക.',
    notice3_title: 'മൺസൂൺ റെയിൻഗാർഡിംഗ് ജൂൺ 10 ന് ആരംഭിക്കുന്നു', notice3_desc: 'മൺസൂണിന് മുമ്പ് റെയിൻഗാർഡ് സ്ട്രിപ്പുകൾ ഉപയോഗിക്കുക. ഫീൽഡ് സൂപ്പർവൈസർ നിർദ്ദേശം നൽകും.',
    my_day: 'എന്റെ ദിവസം', sys_overview: 'സിസ്റ്റം', audit_workspace: 'ഓഡിറ്റ് വർക്ക്സ്പേസ്', my_day_cc: 'എന്റെ ദിവസം · കളക്ഷൻ കേന്ദ്രം',
    sys_sub: 'സർവീസ് ഹെൽത്ത് · ഉപയോക്താക്കൾ · ഇന്റഗ്രേഷൻ · ഓഡിറ്റ്',
    open_settings: 'ക്രമീകരണങ്ങൾ തുറക്കുക', export_findings: 'കണ്ടെത്തലുകൾ ഡൗൺലോഡ് ചെയ്യുക', raise_finding: 'കണ്ടെത്തൽ രേഖപ്പെടുത്തുക',
    good_morning: 'ശുഭദിനം', tappers_today: 'ടാപ്പർമാർ · ഇന്ന്', latex_collected: 'ശേഖരിച്ച ലാറ്റക്സ്', pending_verify: 'ഉറപ്പാക്കാൻ ബാക്കിയുള്ളവ',
    blocks_18_msg: '18 ബ്ലോക്കുകൾ · ഇന്ന് D1 സൈക്കിൾ · 412 ടാപ്പർമാർ', blocks_3_msg: '3 ബ്ലോക്കുകൾ · ഇന്ന് D1 സൈക്കിൾ · 38 ടാപ്പർമാർ',
    open_muster: 'മാസ്റ്റർ തുറക്കുക', add_dps_entry: 'DPS എൻട്രി ചേർക്കുക', record_intake: 'ഇൻടേക്ക് രേഖപ്പെടുത്തുക', issue_ammonia: 'അമോണിയ നൽകുക',
    klp_b07_d1: 'KLP-B07 · D1', pending_verification_9: '9 എണ്ണം ഉറപ്പാക്കാൻ ബാക്കിയുണ്ട്', cc_main_6_batches: 'CC-Main · 6 ബാച്ചുകൾ വരാനുണ്ട്', blocks_awaiting_2: '2 ബ്ലോക്കുകൾ കാത്തിരിക്കുന്നു',
    my_blocks_today_d1: 'എന്റെ ബ്ലോക്കുകൾ · ഇന്ന് (D1 സൈക്കിൾ)', on_track: 'കൃത്യം', drc_low: 'DRC കുറവ്', open_dps: 'DPS തുറക്കുക',
    todo_4_items: 'ചെയ്യേണ്ടവ · 4 എണ്ണം', open: 'തുറക്കുക',
    verify_9_dps: '9 DPS എൻട്രികൾ ഉറപ്പാക്കുക', submitted_by_v_raj: 'V. രാജ് സമർപ്പിച്ചത് · 09:32',
    mark_suresh_absent: 'സുരേഷ് ബാബുവിന് ഹാജരില്ല (3-ാം ദിവസം)', auto_escalate_field_officer: 'ഫീൽഡ് ഓഫീസർക്ക് റിപ്പോർട്ട് ചെയ്യും',
    sample_retest_saritha: 'സാമ്പിൾ വീണ്ടും പരിശോധിക്കുക · സരിത ആനന്ദ്', drc_flagged_cc: 'DRC 31.4% CC-യിൽ ഫ്ലാഗ് ചെയ്തു',
    submit_estimate_est: 'EST-1042 എസ്റ്റിമേറ്റ് സമർപ്പിക്കുക', plus_12_mandays: '+12 തൊഴിൽ ദിനങ്ങൾ · B19 വെട്ടിത്തെളിക്കൽ',
    cc_dash_batches_done: 'പൂർത്തിയായ ബാച്ചുകൾ', cc_dash_retests_due: 'പുനർപരിശോധനകൾ',
    cc_dash_weigh_drc_sample: 'തൂക്കം - DRC സാമ്പിൾ', cc_dash_open_intake_queue: 'ഇൻടേക്ക് ക്യൂ തുറക്കുക',
    cc_dash_batches_awaiting: '6 ബാച്ചുകൾ കാത്തിരിക്കുന്നു', cc_dash_blocks_requested: '2 ബ്ലോക്കുകൾ ആവശ്യപ്പെട്ടു',
    cc_dash_my_muster: 'എന്റെ മാസ്റ്റർ', cc_dash_mark_present: 'ഹാജർ രേഖപ്പെടുത്തുക 07:00',
    cc_dash_last_8_intakes: 'അവസാന 8 ഇൻടേക്ക് · ടാഗ് കാത്തിരിക്കുന്നു', cc_dash_cc_stock_at_hand: 'CC സ്റ്റോക്ക്',
    cc_dash_full_inventory: 'മുഴുവൻ ഇൻവെന്ററി →',
    payroll_sub: 'സൈക്കിൾ 21 Apr – 20 May 2026 · 21 മുതൽ 20 വരെ · 1,623 തൊഴിലാളികൾ',
    recompute: 'വീണ്ടും കണക്കാക്കുക', bank_file_neft: 'ബാങ്ക് ഫയൽ (NEFT)', close_cycle: 'സൈക്കിൾ അവസാനിപ്പിക്കുക',
    gross_wages: 'മൊത്തം വേതനം', lakh: 'ലക്ഷം', gross_wages_sub: '21 Apr – 20 May · 1,623 തൊഴിലാളികൾ',
    avg_wage_worker: 'ശരാശരി വേതനം / തൊഴിലാളി', da_hike_applied: '▲ ₹186 (DA വർദ്ധന)',
    drc_incentive_pool: 'DRC ഇൻസെന്റീവ് തുക', tappers_above_base: 'അടിസ്ഥാനത്തിന് മുകളിൽ 412 ടാപ്പർമാർ',
    variance_flags: 'വ്യത്യാസങ്ങൾ', needs_review_before_close: 'അവസാനിപ്പിക്കുന്നതിന് മുമ്പ് പരിശോധിക്കണം',
    collect_inputs: 'വിവരങ്ങൾ ശേഖരിക്കുക', collect_inputs_sub: 'ഹാജർ + DPS + മസ്ദൂർ',
    compute_wages: 'വേതനം കണക്കാക്കുക', compute_wages_sub: 'സ്ലബ്ബുകൾ · DA · ഇൻസെന്റീവ്',
    review_variances: 'വ്യത്യാസങ്ങൾ പരിശോധിക്കുക', review_variances_sub: '12 വ്യത്യാസങ്ങൾ കണ്ടെത്തി',
    approval_ladder: 'അനുമതി', approval_ladder_sub: 'EM → GM → MD',
    disburse: 'വിതരണം ചെയ്യുക', disburse_sub: 'KSB-ലേക്ക് NEFT ബാച്ച്',
    payslip_release: 'പേസ്ലിപ്പ് നൽകുക', payslip_release_sub: 'EN + ML PDF-കൾ · SMS ലിങ്ക്',
    wage_variance_needs_review: 'വേതനത്തിലെ വ്യത്യാസം · പരിശോധിക്കുക', flags_12: '12 ഫ്ലാഗുകൾ',
    worker_lbl: 'തൊഴിലാളി', last_cycle: 'കഴിഞ്ഞ സൈക്കിൾ', this_cycle: 'ഈ സൈക്കിൾ', delta: 'Δ', reason: 'കാരണം',
    drc_inc_up: 'DRC ഇൻസെന്റീവ് ▲', days_3_absent: '3 ദിവസം ഹാജരില്ല', ot_12_hrs: 'OT 12 മണിക്കൂർ', drc_hl_up: 'DRC + ചുമട് ▲', low_drc_pen: 'DRC കുറഞ്ഞതിനുള്ള പിഴ',
    comp_gross_wages: 'മൊത്തം വേതനത്തിന്റെ ഘടന · ₹68.4 ലക്ഷം', basic_wages: 'അടിസ്ഥാന വേതനം', da: 'ക്ഷാമബത്ത (DA)',
    hra: 'വീട്ടുവാടക (HRA)', hl_slab: 'ചുമട്ടു കൂലി (സ്ലബ്ബ് പ്രകാരം)', drc_yield_inc: 'DRC / ഉൽപാദന ഇൻസെന്റീവ്', overtime: 'ഓവർടൈം',
    mid_cycle_da_applied: 'ഈ സൈക്കിളിലെ DA വർദ്ധന: ₹186/തൊഴിലാളി × 1,623 = ₹3,01,878',
    mid_cycle_da_sub: '28-Apr-2026 ലെ GO(Rt) നം. 412/2026/Lab പ്രകാരം. 21-Apr മുതൽ 28-Apr വരെ പഴയ നിരക്കും, 29-Apr മുതൽ പുതിയ നിരക്കും.',
    cycle_preview: 'സൈക്കിൾ പ്രിവ്യൂ · എല്ലാ തൊഴിലാളികളും',
    days_lbl: 'ദിവസങ്ങൾ', basic_lbl: 'അടിസ്ഥാനം', da_lbl: 'DA', hl_lbl: 'HL', incentive_lbl: 'ഇൻസെന്റീവ്', gross_lbl: 'മൊത്തം', deduct_lbl: 'കിഴിവുകൾ', net_lbl: 'അറ്റ വേതനം',
    review_badge: 'പരിശോധിക്കുക', ok_badge: 'ശരി', showing_8_of: '1,623 ൽ 8 എണ്ണം കാണിക്കുന്നു · ആകെ തുക റിപ്പോർട്ടിന്റെ താഴെ',
    view_full_register: 'മുഴുവൻ രജിസ്റ്ററും കാണുക', submit_for_approval: 'അനുമതിക്കായി സമർപ്പിക്കുക',
    payslip_sub: 'രാജൻ പിള്ള · EMP-1042 · സൈക്കിൾ 21 Apr – 20 May 2026',
    pdf_en: 'PDF (EN)', pdf_ml: 'PDF (ML)', download_pdf: 'PDF ഡൗൺലോഡ് ചെയ്യുക', sms_to_worker: 'തൊഴിലാളിക്ക് SMS അയക്കുക',
    variant: 'വേരിയന്റ്', official: 'ഔദ്യോഗികം', malayalam: 'മലയാളം', mobile_sms: 'മൊബൈൽ/SMS'
  }
};

@Component({
  selector: 'app-bi',
  standalone: true,
  template: `
    @if (lang() === 'both') {
      <ng-container>{{ enText }} <span class="ml muted" style="font-weight: 400; font-size: 0.92em;">· {{ mlText }}</span></ng-container>
    } @else if (lang() === 'ml') {
      <span class="ml">{{ mlText }}</span>
    } @else {
      <ng-container>{{ enText }}</ng-container>
    }
  `,
  styles: [':host { display: inline; }']
})
export class BiComponent {
  @Input({ required: true }) k!: string;
  @Input() overrideLang?: string;

  private config = inject(AppConfigService);

  get lang() {
    return computed(() => this.overrideLang || this.config.lang());
  }

  get enText() {
    return TRANSLATIONS['en'][this.k] || this.k;
  }

  get mlText() {
    return TRANSLATIONS['ml'][this.k] || this.k;
  }
}
